apiVersion: 1

provisioningConfigUpdateFrequencySeconds: 10
disableDeletion: false

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    jsonData:
      timeInterval: 10s
    isDefault: false
    editable: true

  - name: VictoriaMetrics
    type: prometheus
    access: proxy
    url: http://victoriametrics:8428
    jsonData:
      timeInterval: 10s
    isDefault: true
    editable: true
